package com.ejobfinder.utils.consts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class TechnologiesConst {

    public static final List<String> TECHNOLOGY_LIST = new ArrayList<>(Arrays.asList(
            "ActionScript"
            , ".NET"
            , "Active"
            , "Directory"
            , "Ajax"
            , "ASP"
            , "ASP.NET"
            , "MVC"
            , "Assembler"
            , "C"
            , "C#"
            , "C/AL"
            , "C++"
            , "Clojure"
            , "Cobol"
            , "II"
            , "Cognos"
            , "Dart"
            , "Delphi"
            , "Flash"
            , "Groovy"
            , "HTML"
            , "Informix"
            , "4GL"
            , "Java"
            , "JavaScript"
            , "AngularJS"
            , "jQuery"
            , "NodeJS"
            , "SpringMVC"
            , "JSON"
            , "LINQ"
            , "Lucene"
            , "Matlab"
            , "Natural"
            , "Hibernate"
            , "NoSQL"
            , "ObjectiveC"
            , "Perl"
            , "PHP"
            , "PL/SQL"
            , "Powershell"
            , "Python"
            , "QML"
            , "Qt"
            , "RPG"
            , "Ruby"
            , "SAP"
            , "ABAP"
            , "SAS"
            , "Scala"
            , "Solr"
            , "Spring"
            , "SQL_"
            , "Swing"
            , "UML"
            , "VB"
            , "WCF"
            , "Web"
            , "WebServices"
            , "WinForms"
            , "WPF"
            , "Xpp"
            , "XCode"
            , "XMaL"
            , "XSLT"
            , "CSS"
            , "J2EE"
            , "XML"
            , "REST"
            , "SOAP"
    ));
}
