package drools.templates;
global com.ejobfinder.model.Candidate candidate
import com.ejobfinder.model.TechnologyFact;
dialect "java"

rule "2 - technology rule 3"
when
  com.ejobfinder.model.TechnologyFact((name == "SQL") && (level >= 3) && (year >= 3.0))
then
  candidate.score(1);
end

rule "1 - technology rule 2"
when
  com.ejobfinder.model.TechnologyFact((name == "Spring") && (level >= 2) && (year >= 1.0))
then
  candidate.score(3);
end

rule "0 - technology rule 1"
when
  com.ejobfinder.model.TechnologyFact((name == "Java") && (level >= 3) && (year >= 2.0))
then
  candidate.score(2);
end


