template header

name
object
conditional
action

package drools.templates;

global com.ejobfinder.model.Candidate candidate
import com.ejobfinder.model.facts.TechnologyFact;
import com.ejobfinder.model.facts.SkillFact;
import com.ejobfinder.model.facts.WorkingHoursFact;


dialect "java"

template "Perfect Employee Rules"

rule "@{row.rowNumber} - @{name}"
when
  @{object}(@{conditional})
then
  candidate.score(@{action});
end

end template