template header

name
object
conditional
action

package drools.templates;

global com.ejobfinder.model.Candidate candidate
import com.ejobfinder.model.facts.TechnologyFact;
import com.ejobfinder.model.facts.SkillFact;
import com.ejobfinder.model.facts.WorkingHoursFact;
import com.ejobfinder.model.facts.EducationFact;
import com.ejobfinder.model.facts.LanguageFact;
import com.ejobfinder.model.facts.LocationFact;
import com.ejobfinder.model.facts.PeriodOfNoticeFact;
import com.ejobfinder.model.facts.PreviousEmployerFact;
import com.ejobfinder.model.facts.SalaryFact;
import com.ejobfinder.model.facts.ToolFact;
import com.ejobfinder.model.facts.TypeOfContractFact;


dialect "java"

template "Perfect Employee Rules"

rule "@{row.rowNumber} - @{name}"
when
  @{object}(@{conditional})
then
  candidate.score(@{action})
end

end template